function [Kdyn] = DynamicConstBeam(E,L,A,I,rho,wi)
% Dr Alessandro Tombari - https://github.com/AntroxEV
%Dynamic Stiffness Matrix of Prismatic Euler Beam (distributed mass)
% 2 x 2 (2D Plane) Matrix - 2 DOFS displacement and rotation
% INPUT (singleton - scalar values):
% E: Elastic Modulus
% I: cross-sectional second moment of area
% L: beam length
% rho: unit mass density 
% wi: frequency
% OUTPUT:
%Kdyn: 2x2 Stiffness Matrix (frequency depedent)


Kdyn =[-(E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4)) + cosh(L*((A*rho*wi^2)/(E*I))^(1/4))*sin(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(3/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                         -(E*I*sin(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                       (E*I*(sin(L*((A*rho*wi^2)/(E*I))^(1/4)) + sinh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(3/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                      (E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1);
        -(E*I*sin(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1), (E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4))*sin(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                      -(E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                      (E*I*(sin(L*((A*rho*wi^2)/(E*I))^(1/4)) - sinh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1);
        (E*I*(sin(L*((A*rho*wi^2)/(E*I))^(1/4)) + sinh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(3/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                     -(E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1), -(E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4)) + cosh(L*((A*rho*wi^2)/(E*I))^(1/4))*sin(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(3/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                          (E*I*sin(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1);
       (E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                      (E*I*(sin(L*((A*rho*wi^2)/(E*I))^(1/4)) - sinh(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1),                                                                           (E*I*sin(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4))*((A*rho*wi^2)/(E*I))^(1/2))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1), (E*I*(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*sinh(L*((A*rho*wi^2)/(E*I))^(1/4)) - cosh(L*((A*rho*wi^2)/(E*I))^(1/4))*sin(L*((A*rho*wi^2)/(E*I))^(1/4)))*((A*rho*wi^2)/(E*I))^(1/4))/(cos(L*((A*rho*wi^2)/(E*I))^(1/4))*cosh(L*((A*rho*wi^2)/(E*I))^(1/4)) - 1)];
end